### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by ncobb01** [gitsah/MicroMomentums#10]
As a user I would like a clean interface for viewing stocks and the changes that occur on given five minute increments

**Comment by ncobb01** [comment]
Color palette changes?

**Comment by ncobb01** [comment]
Description bar / key for how app is used

**Comment by ncobb01** [comment]
Changes to arrows

**Comment by ncobb01** [comment]
updating the check's and x's

**Comment by jameriah30** [comment]
Further updated the ui to match color scheme
